// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsuicavybrvrovlgfviz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzdWljYXZ5YnJ2cm92bGdmdml6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1OTExMzUsImV4cCI6MjA3MTE2NzEzNX0.sKk3DkUBhmofYLF86NT-lqC_rRKQrlMrlMgr4GRq7Bk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  } 
});